/* build_questions.js — quality gate + compiler (Phase 1).
   Reads every JSON under /content/questions (recursively) and:
     1. VALIDATES each question (schema, answer, metadata).
     2. Resolves STATUS lifecycle: draft -> ai_generated -> pending_verification -> verified -> published -> archived.
        ONLY status "published" is compiled into the app. (Unverified => pending, never shown.)
     3. DEDUPLICATES (exact match on stem + options).
     4. Emits app bundles data/questions/<subject>.js (published only).
     5. Emits data/stats.js (window.BANK_STATS) for the Admin dashboard.
     6. Writes content/questions/PROGRESS.md + a validation report.
   Run: node tools/build_questions.js */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "content", "questions");
const QDIR = path.join(ROOT, "data", "questions");
const PHASE1_PER_SUBJECT = 200, PHASE1_TOTAL = 1000;
const FOLDER_TO_APP = { quant: "quantitative", verbal: "verbal", reasoning: "reasoning", gk: "general_awareness", computer: "computer" };
const APP_SUBS = ["computer", "general_awareness", "quantitative", "reasoning", "verbal"];
const VALID_SOURCE = ["Verified Previous Year Question","Repeated Previous Year Question","Verified Competitive Question","Standard Textbook Question","Verified Model Question","AI Generated (Verified)"];
const STATUSES = ["draft","ai_generated","pending_verification","verified","published","archived"];

function walk(dir){ let o=[]; if(!fs.existsSync(dir))return o; for(const f of fs.readdirSync(dir)){ const p=path.join(dir,f); if(fs.statSync(p).isDirectory())o=o.concat(walk(p)); else if(f.endsWith(".json"))o.push(p);} return o; }
function norm(s){ return String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim(); }
function resolveStatus(q){ if(q.status && STATUSES.includes(q.status)) return q.status; return q.verificationStatus==="verified" ? "published" : "pending_verification"; }

function validate(q){
  const e=[];
  ["id","subject","topic","difficulty","question","options","answer","explanation","importance","sourceType"].forEach(k=>{ if(q[k]===undefined||q[k]===null||q[k]==="") e.push("missing "+k); });
  if(!Array.isArray(q.options)||q.options.length!==4) e.push("options must be exactly 4");
  else if(new Set(q.options.map(o=>String(o).trim().toLowerCase())).size!==4) e.push("options not distinct");
  if(typeof q.answer!=="number"||q.answer<0||q.answer>3) e.push("answer must be index 0-3");
  if(!["Easy","Medium","Hard","Expert"].includes(q.difficulty)) e.push("bad difficulty");
  if(q.importance<1||q.importance>5) e.push("importance 1-5");
  if(!VALID_SOURCE.includes(q.sourceType)) e.push("invalid sourceType");
  if(String(q.explanation||"").length<8) e.push("explanation too short");
  if(!Array.isArray(q.tags)||q.tags.length===0) e.push("empty tags");
  return e;
}

function run(){
  const files=walk(OUT);
  const published={}, all=[], seen=new Map(), ids=new Set();
  const byStatus={}; STATUSES.forEach(s=>byStatus[s]=0);
  let accepted=0, rejected=0, dupes=0, idDup=0;
  const issues=[];

  files.forEach(file=>{
    let arr; try{ arr=JSON.parse(fs.readFileSync(file,"utf8")); }catch(e){ issues.push("JSON parse error: "+path.relative(ROOT,file)); return; }
    if(!Array.isArray(arr)){ issues.push("not an array: "+path.relative(ROOT,file)); return; }
    arr.forEach(q=>{
      const errs=validate(q);
      if(ids.has(q.id)){ idDup++; errs.push("duplicate ID"); }
      if(errs.length){ rejected++; issues.push(q.id+" ("+path.basename(file)+"): "+errs.join(", ")); return; }
      ids.add(q.id);
      const key=norm(q.question+" || "+q.options.join(" | "));
      if(seen.has(key)){ dupes++; issues.push(q.id+": duplicate of "+seen.get(key)); return; }
      seen.set(key,q.id);
      const status=resolveStatus(q); byStatus[status]=(byStatus[status]||0)+1;
      all.push(q);
      if(status==="published"){ const s=FOLDER_TO_APP[q.subject]||q.subject; (published[s]=published[s]||[]).push(q); accepted++; }
    });
  });

  // emit app bundles (published only)
  Object.keys(FOLDER_TO_APP).forEach(folder=>{
    const s=FOLDER_TO_APP[folder];
    const list=(published[s]||[]).sort((a,b)=>b.importance-a.importance)
      .map(q=>({id:q.id,topic:q.topic,q:q.question,options:q.options,answer:q.answer,exp:q.explanation,diff:q.difficulty[0],imp:q.importance,tags:q.tags||[],src:q.sourceType}));
    fs.writeFileSync(path.join(QDIR,s+".js"),
      "/* AUTO-GENERATED by tools/build_questions.js from content/questions/. Do not edit. */\nwindow.QDATA=window.QDATA||{};\nwindow.QDATA."+s+"="+JSON.stringify(list)+";\n");
  });

  // per-subject stats
  const perSubject={}; let grandPub=0;
  APP_SUBS.forEach(s=>{
    const pub=published[s]||[];
    const topics=new Set(pub.map(q=>q.topic));
    const diff={Easy:0,Medium:0,Hard:0,Expert:0}; pub.forEach(q=>diff[q.difficulty]++);
    perSubject[s]={ published:pub.length, target:PHASE1_PER_SUBJECT, coverageTopics:topics.size, difficulty:diff };
    grandPub+=pub.length;
  });

  const stats={ generated:new Date().toISOString().slice(0,10), phase:"Phase 1",
    target:{perSubject:PHASE1_PER_SUBJECT,total:PHASE1_TOTAL},
    totals:{published:grandPub, allTracked:all.length, accepted:accepted, rejected:rejected, duplicatesBlocked:dupes, duplicateIds:idDup},
    byStatus:byStatus, perSubject:perSubject, issues:issues.slice(0,100) };
  fs.writeFileSync(path.join(QDIR,"..","stats.js"),
    "/* AUTO-GENERATED. Admin dashboard stats. */\nwindow.BANK_STATS="+JSON.stringify(stats,null,1)+";\n");

  // PROGRESS.md
  let md="# Question Bank — Phase 1 Progress\n\n_Auto-generated "+stats.generated+"._\n\n";
  md+="| Subject | Published | Target | % | Topics | Easy/Med/Hard/Exp |\n|---|---|---|---|---|---|\n";
  APP_SUBS.forEach(s=>{ const p=perSubject[s]; md+="| "+s+" | "+p.published+" | "+p.target+" | "+Math.round(p.published/p.target*100)+"% | "+p.coverageTopics+" | "+p.difficulty.Easy+"/"+p.difficulty.Medium+"/"+p.difficulty.Hard+"/"+p.difficulty.Expert+" |\n"; });
  md+="| **TOTAL** | **"+grandPub+"** | **"+PHASE1_TOTAL+"** | **"+Math.round(grandPub/PHASE1_TOTAL*100)+"%** | | |\n\n";
  md+="**Status lifecycle:** "+STATUSES.map(s=>s+"="+byStatus[s]).join(" · ")+"\n\n";
  md+="Accepted(published): "+accepted+" · Rejected: "+rejected+" · Duplicates blocked: "+dupes+" · Duplicate IDs: "+idDup+"\n\n";
  if(issues.length) md+="## Validation issues ("+issues.length+")\n\n- "+issues.slice(0,60).join("\n- ")+"\n";
  else md+="_No validation issues. All published questions passed the gate._\n";
  fs.writeFileSync(path.join(OUT,"PROGRESS.md"),md);

  console.log("QUALITY GATE — PHASE 1");
  console.log("  published: "+grandPub+" / "+PHASE1_TOTAL+" ("+Math.round(grandPub/PHASE1_TOTAL*100)+"%)");
  console.log("  status: "+STATUSES.map(s=>s+"="+byStatus[s]).join(" · "));
  console.log("  rejected: "+rejected+" · dup-text: "+dupes+" · dup-id: "+idDup);
  if(issues.length) console.log("  issues (first 5):\n   - "+issues.slice(0,5).join("\n   - "));
  console.log("  -> data/questions/*.js, data/stats.js, content/questions/PROGRESS.md");
}
run();
